language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

services:
  - mongodb

before_script: 
 - mongorestore farmer_dump
 - mongorestore storage_dump

script:
  - coverage run --source="driveshare-graph" setup.py test

after_success:
  - coveralls

notifications:
  email: false
