language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - coverage run --source="driveshare-graph" setup.py test

after_success:
  - coveralls

notifications:
  email: false
