language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

services:
  - mongodb

before_script: 
 - mongorestore --port 27017 --db GroupB tests/dump/GroupB
 - mongorestore --port 27017 --db GroupB tests/storage_dump/GroupB
 - bash travis_setup.sh

script:
  - export DATASERV_HOST="127.0.0.1:5000"
  - coverage run --source="driveshare_graph" setup.py test

after_success:
  - coveralls

notifications:
  email: false
