language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

services:
  - mongodb

before_script: 
 - mongorestore --port 27017 --db GroupB farmer_dump/GroupB
 - mongorestore --port 27017 --db GroupB storage_dump/GroupB

script:
  - coverage run --source="driveshare_graph" setup.py test

after_success:
  - coveralls

notifications:
  email: false
